module.exports = {
	text_case1: { code: "", name: "", email: "", password: "" },
	text_case2: { code: "aaa", name: "", email: "", password: "" },
	text_case3: {
		code: "aaaaaaaaaaaaaaaaaaaaa",
		name: "",
		email: "",
		password: "",
	},
	text_case4: {
		code: "あああああ",
		name: "",
		email: "",
		password: "",
	},
	text_case5: {
		code: "",
		name: "aaaaaaaaaaaaaaaaaaaaa",
		email: "",
		password: "",
	},
	text_case6: {
		code: "",
		name: "",
		email: "aaaaaaa",
		password: "",
	},
	text_case7: {
		code: "",
		name: "",
		email: "",
		password: "hoge",
		passwordConfirmation: "foo",
	},
	text_case8: {
		code: "",
		name: "",
		email: "",
		password: "hoge",
	},
	text_case9: {
		code: "",
		name: "",
		email: "",
		password: "aaaaaaaaaaaaaaaaaaaaa",
	},
	text_case10: {
		code: "",
		name: "",
		email: "",
		password: "ああああああ",
	},
	text_case11: {
		code: "nakajima",
		name: "nakajima",
		email: "nakajima.shunsuke@gmail.com",
		password: "eruze9370",
		passwordConfirmation: "eruze9370",
	},
};
